version: 2.1
orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.4
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run test
      - run:
          command: npm run test:cov
      - codecov/upload
workflows:
  build-and-test:
    jobs:
      - build-and-test
